version: '2'
services:
    jhipstersampleapp-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/jhipsterSampleApp/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=jhipsterSampleApp
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
